#!/usr/bin/env python3
"""Colorpedia maintenance tool (Python 3.8+, standard library only).

Commands
  import   Merge the name lists in data/sources/*.json into colors.json.
  build    Recompute the hex color map and write it into index.html,
           refresh meta counts in colors.json.
  check    Validate colors.json and the map in index.html (exit 1 on error).
  all      import + build + check.

The layout rules implemented here are documented in okf/map/layout-rules.md.
"""
import colorsys
import html
import json
import math
import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COLORS_JSON = ROOT / "colors.json"
INDEX_HTML = ROOT / "index.html"
SOURCES = ROOT / "data" / "sources"

MAP_BEGIN = "<!-- COLORMAP:BEGIN generated by tools/colorpedia.py build - do not edit by hand -->"
MAP_END = "<!-- COLORMAP:END -->"

# --- Grid geometry (flat-top hexagons, "odd-q" offset columns) -------------
HEX_R = 10.0                      # circumradius of one hexagon
COL_STEP = 1.5 * HEX_R            # 15   horizontal distance between columns
ROW_STEP = math.sqrt(3) * HEX_R   # 17.32 vertical distance between rows
MARGIN = 20.0                     # free space around the outermost cells

# --- Colour-wheel orientation ----------------------------------------------
# Angles are mathematical (0 deg = right, counter-clockwise, y axis up).
# SEAM is the direction of the neutral (grey) spoke; black sits at its end.
# Hue increases clockwise on screen, starting at the seam: magenta -> red ->
# orange -> yellow -> green -> cyan -> blue -> violet and back to the seam.
SEAM_DEG = 270.0                  # straight down
SEAM_HUE = 293.0                  # HSL hue that sits right next to the seam
NEUTRAL_CHROMA = 6.0              # CIELAB C* below this -> neutral spoke
HUE_EQUALIZE = 0.75                # 0 = angle is pure hue, 1 = angle is pure hue rank

FAMILIES = ["Neutrals", "Reds", "Oranges", "Yellows", "Greens",
            "Blues", "Purples", "Pinks", "Browns"]
NAME_FIELDS = ["names_en", "names_de", "names_ja", "names_brand"]


# --- Colour maths ------------------------------------------------------------
def hex_to_rgb01(hx):
    return tuple(int(hx[i:i + 2], 16) / 255 for i in (1, 3, 5))


def rgb_to_lab(rgb):
    def lin(u):
        return u / 12.92 if u <= 0.04045 else ((u + 0.055) / 1.055) ** 2.4
    r, g, b = (lin(u) for u in rgb)
    x = (0.4124564 * r + 0.3575761 * g + 0.1804375 * b) / 0.95047
    y = 0.2126729 * r + 0.7151522 * g + 0.0721750 * b
    z = (0.0193339 * r + 0.1191920 * g + 0.9503041 * b) / 1.08883

    def f(t):
        return t ** (1 / 3) if t > 216 / 24389 else (24389 / 27 * t + 16) / 116
    fx, fy, fz = f(x), f(y), f(z)
    return 116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz)


def features(hx):
    rgb = hex_to_rgb01(hx)
    L, a, b = rgb_to_lab(rgb)
    hue = colorsys.rgb_to_hls(*rgb)[0] * 360
    return {"L": L, "a": a, "b": b, "C": math.hypot(a, b), "hue": hue}


def norm_name(s):
    s = unicodedata.normalize("NFKD", str(s)).lower()
    s = "".join(ch for ch in s if not unicodedata.combining(ch))
    return re.sub(r"[\s_\-'’.()]+", "", s)


# --- I/O ------------------------------------------------------------------------
def load_colors():
    return json.loads(COLORS_JSON.read_text(encoding="utf-8"))


def save_colors(data):
    COLORS_JSON.write_text(json.dumps(data, ensure_ascii=False, separators=(",", ":")),
                           encoding="utf-8")


def ensure_fields(c):
    for f in NAME_FIELDS:
        c.setdefault(f, [])
    return c


# --- import ---------------------------------------------------------------------
# German "names" that are only an adjective ("dark", "deep", ...) are leftovers
# of a broken automatic translation and carry no information.
BROKEN_DE = {"dunkel", "tief", "mittel", "satt", "blass", "kräftig", "leuchtend", "hell"}


def classify_family(hx):
    """Rule-based colour family (see okf/data/families.md). Order of the tests matters."""
    rgb = hex_to_rgb01(hx)
    h, l, _ = colorsys.rgb_to_hls(*rgb)
    h *= 360
    v = max(rgb)
    f = features(hx)
    if f["C"] < 8 or (f["L"] > 96 and f["C"] < 12):
        return "Neutrals"
    if 15 <= h < 55 and v < 0.72:
        return "Browns"
    if h >= 345 or h < 12:
        return "Pinks" if l > 0.72 else "Reds"
    if h < 40:
        return "Oranges"
    if h < 68:
        return "Yellows"
    if h < 165:
        return "Greens"
    if h < 250:
        return "Blues"
    if h < 290:
        return "Purples"
    return "Pinks"


def cmd_import():
    data = load_colors()
    colors = [ensure_fields(c) for c in data["colors"]]
    by_hex = {c["hex"]: c for c in colors}

    removed = 0
    for c in colors:
        before = len(c["names_de"])
        c["names_de"] = [n for n in c["names_de"] if n.strip().lower() not in BROKEN_DE]
        removed += before - len(c["names_de"])

    used = {f: {norm_name(n) for c in colors for n in c[f]} for f in NAME_FIELDS}
    added_hex, added_names = 0, 0

    def entry(hx):
        nonlocal added_hex
        if hx not in by_hex:
            c = ensure_fields({"hex": hx, "family": None})
            by_hex[hx] = c
            colors.append(c)
            added_hex += 1
        return by_hex[hx]

    def add(field, hx, name, extra=None):
        nonlocal added_names
        key = norm_name(name)
        if not key or key in used[field]:
            return False          # names stay unique per language
        c = entry(hx)
        c[field].append(name)
        used[field].add(key)
        added_names += 1
        if extra:
            extra(c)
        return True

    for src in sorted(SOURCES.glob("*.json")):
        s = json.loads(src.read_text(encoding="utf-8"))
        field = {"en": "names_en", "de": "names_de", "ja": "names_ja"}[s["lang"]]
        for item in s["colors"]:
            hx = item["hex"].lower()
            if not re.fullmatch(r"#[0-9a-f]{6}", hx):
                raise SystemExit(f"{src.name}: bad hex {item['hex']}")
            if field == "names_ja":
                romaji = item.get("romaji")
                add(field, hx, item["name"],
                    lambda c: c.setdefault("names_ja_romaji", []).append(romaji))
            elif "code" in item:
                add(field, hx, item["name"],
                    lambda c: c.setdefault("codes", []).append(item["code"]))
            else:
                add(field, hx, item["name"])

    refamilied = 0
    for c in colors:
        fam = classify_family(c["hex"])
        if c.get("family") and c["family"] != fam:
            refamilied += 1
        c["family"] = fam

    data["colors"] = colors
    update_meta(data)
    save_colors(data)
    print(f"import: removed {removed} broken German names, added {added_names} names, "
          f"{added_hex} new colors -> {len(colors)} colors; {refamilied} family labels corrected")


def update_meta(data):
    cs = data["colors"]
    data["meta"] = {
        "count_raw": sum(len(c.get(f, [])) for c in cs for f in NAME_FIELDS),
        "count_unique": len(cs),
    }


# --- build (layout) --------------------------------------------------------------
def cell_center(col, row):
    x = col * COL_STEP
    y = row * ROW_STEP + (ROW_STEP / 2 if col % 2 else 0)
    return x, y


def neighbours(col, row):
    if col % 2 == 0:
        d = [(0, -1), (0, 1), (-1, -1), (-1, 0), (1, -1), (1, 0)]
    else:
        d = [(0, -1), (0, 1), (-1, 0), (-1, 1), (1, 0), (1, 1)]
    return [(col + a, row + b) for a, b in d]


def layout(colors):
    """Return {hex: (col, row)} for all colours. Deterministic."""
    n = len(colors)
    # 1) the n grid cells closest to the centre form a round disc
    span = int(math.sqrt(n)) + 4
    cells = []
    for col in range(-span, span + 1):
        for row in range(-span, span + 1):
            x, y = cell_center(col, row)
            cells.append((math.hypot(x, y), math.atan2(-y, x), col, row))
    cells.sort()
    cells = [(c[2], c[3]) for c in cells[:n]]
    pos = {c: cell_center(*c) for c in cells}
    r_max = max(math.hypot(*p) for p in pos.values()) + 0.5 * HEX_R

    # 2) a target point per colour: radius from lightness rank, angle from hue
    feats = {c["hex"]: features(c["hex"]) for c in colors}
    by_light = sorted(colors, key=lambda c: (-feats[c["hex"]]["L"], c["hex"]))
    neutrals = [c for c in colors if feats[c["hex"]]["C"] < NEUTRAL_CHROMA]
    wedge = 360.0 * len(neutrals) / n
    # hue position u (0..360, clockwise from the seam). It is blended with the
    # hue *rank* so that crowded hue ranges (reds, blues) get proportionally
    # more of the circle; otherwise they push the white core off-centre.
    chrom = sorted((c for c in colors if feats[c["hex"]]["C"] >= NEUTRAL_CHROMA),
                   key=lambda c: ((feats[c["hex"]]["hue"] - SEAM_HUE) % 360.0, c["hex"]))
    u_pos = {}
    for i, c in enumerate(chrom):
        raw = (feats[c["hex"]]["hue"] - SEAM_HUE) % 360.0
        u_pos[c["hex"]] = (1 - HUE_EQUALIZE) * raw + HUE_EQUALIZE * 360.0 * (i + 0.5) / len(chrom)
    target = {}
    for rank, c in enumerate(by_light):
        f = feats[c["hex"]]
        radius = r_max * math.sqrt((rank + 0.5) / n)
        if f["C"] < NEUTRAL_CHROMA:
            ang = SEAM_DEG
        else:
            ang = SEAM_DEG - wedge / 2 - (360.0 - wedge) * u_pos[c["hex"]] / 360.0
        a = math.radians(ang)
        target[c["hex"]] = (radius * math.cos(a), -radius * math.sin(a))

    def cost(hx, cell):
        tx, ty = target[hx]
        x, y = pos[cell]
        return (x - tx) ** 2 + (y - ty) ** 2

    # 3) greedy: lightest first, each colour takes the free cell nearest its target.
    #    The lightest colour (white) is pinned to the centre cell (0, 0).
    free = set(cells)
    at = {(0, 0): by_light[0]["hex"]}
    free.remove((0, 0))
    for c in by_light[1:]:
        hx = c["hex"]
        best = min(free, key=lambda cell: (cost(hx, cell), cell))
        free.remove(best)
        at[best] = hx

    # 4) local search: swap two cells whenever that lowers the total distance
    cell_list = sorted(set(cells) - {(0, 0)})
    near = {}
    for cell in cell_list:
        ring, seen = [cell], {cell}
        for _ in range(2):                                # up to 2 steps away
            ring = [nb for r in ring for nb in neighbours(*r)
                    if nb in pos and nb != (0, 0) and nb not in seen]
            seen.update(ring)
        near[cell] = sorted(seen - {cell})
    improved = True
    passes = 0
    while improved and passes < 200:
        improved = False
        passes += 1
        for a in cell_list:
            for b in near[a]:
                ha, hb = at[a], at[b]
                if cost(ha, b) + cost(hb, a) + 1e-9 < cost(ha, a) + cost(hb, b):
                    at[a], at[b] = hb, ha
                    improved = True
    return {hx: cell for cell, hx in at.items()}


def fmt(v):
    return f"{v:.2f}"


def display_name(raw):
    s = str(raw).strip()
    if " " not in s:
        s = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", s.replace("_", " "))
    return s


def svg_for(colors, placement):
    xs, ys = [], []
    for col, row in placement.values():
        x, y = cell_center(col, row)
        xs.append(x)
        ys.append(y)
    ox = MARGIN + HEX_R - min(xs)
    oy = MARGIN + ROW_STEP / 2 - min(ys)
    w = max(xs) - min(xs) + 2 * (MARGIN + HEX_R)
    h = max(ys) - min(ys) + 2 * (MARGIN + ROW_STEP / 2)
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {fmt(w)} {fmt(h)}" '
           f'width="{fmt(w)}" height="{fmt(h)}" shape-rendering="crispEdges">',
           '<g stroke="#444444" stroke-width="1" stroke-opacity="0.25">']
    # row-major order (top to bottom, left to right) keeps the file diff-friendly
    order = sorted(colors, key=lambda c: (cell_center(*placement[c["hex"]])[1],
                                          cell_center(*placement[c["hex"]])[0]))
    for c in order:
        col, row = placement[c["hex"]]
        cx, cy = cell_center(col, row)
        cx, cy = cx + ox, cy + oy
        pts = " ".join(f"{fmt(cx + HEX_R * math.cos(math.radians(k)))},"
                       f"{fmt(cy + HEX_R * math.sin(math.radians(k)))}"
                       for k in (0, 60, 120, 180, 240, 300))
        names = [display_name(n) for f in ("names_en", "names_de") for n in c.get(f, [])]
        names += [f"{n} · {r}" if r else n
                  for n, r in zip(c.get("names_ja", []), c.get("names_ja_romaji", []))]
        names += c.get("names_brand", [])
        label = html.escape(" · ".join(names), quote=True)
        out.append(f'  <polygon points="{pts}" fill="{c["hex"]}" data-hex="{c["hex"]}" '
                   f'data-name="{label}"><title>{label} {c["hex"]}</title></polygon>')
    out.append("</g>")
    out.append("</svg>")
    return "\n".join(out)


def cmd_build():
    data = load_colors()
    colors = [ensure_fields(c) for c in data["colors"]]
    placement = layout(colors)
    svg = svg_for(colors, placement)
    page = INDEX_HTML.read_text(encoding="utf-8")
    block = f'{MAP_BEGIN}\n<div class="mapPane active" data-map="hex">\n{svg}\n</div>\n{MAP_END}'
    if MAP_BEGIN in page:
        start = page.index(MAP_BEGIN)
        end = page.index(MAP_END) + len(MAP_END)
    else:
        # first run: replace the hand-maintained block (incl. stray <?xml?> line)
        start = page.index('<?xml version="1.0" encoding="UTF-8"?>')
        end = page.index("</div>", page.index("</svg>", start)) + len("</div>")
    page = page[:start] + block + page[end:]
    INDEX_HTML.write_text(page, encoding="utf-8")
    # stable colors.json order = map order (lightest first)
    feats = {c["hex"]: features(c["hex"]) for c in colors}
    data["colors"] = sorted(colors, key=lambda c: (-feats[c["hex"]]["L"], c["hex"]))
    update_meta(data)
    save_colors(data)
    print(f"build: {len(colors)} cells written to index.html")


# --- check ------------------------------------------------------------------------
def map_cells(page):
    block = page[page.index(MAP_BEGIN):page.index(MAP_END)]
    cells = []
    for m in re.finditer(r'<polygon points="([^"]+)" fill="([^"]+)" data-hex="([^"]+)"', block):
        pts = [tuple(map(float, p.split(","))) for p in m.group(1).split()]
        cells.append((pts, m.group(2), m.group(3)))
    return cells


def cmd_check():
    errors, warnings = [], []
    data = load_colors()
    colors = data["colors"]
    hexes = [c["hex"] for c in colors]
    if len(set(hexes)) != len(hexes):
        errors.append("duplicate hex in colors.json")
    for c in colors:
        if not re.fullmatch(r"#[0-9a-f]{6}", c["hex"]):
            errors.append(f"bad hex {c['hex']}")
        if c.get("family") != classify_family(c["hex"]):
            errors.append(f"{c['hex']}: family {c.get('family')} != rule {classify_family(c['hex'])}")
        if not any(c.get(f) for f in NAME_FIELDS):
            errors.append(f"{c['hex']}: has no name")
        if len(c.get("names_ja", [])) != len(c.get("names_ja_romaji", [])):
            errors.append(f"{c['hex']}: names_ja / names_ja_romaji length mismatch")
    for f in ("names_en", "names_de", "names_ja"):
        seen = {}
        for c in colors:
            for n in c.get(f, []):
                k = norm_name(n)
                if k in seen and seen[k] != c["hex"]:
                    warnings.append(f"{f}: '{n}' used for {seen[k]} and {c['hex']}")
                seen.setdefault(k, c["hex"])
    meta = data.get("meta", {})
    expect = sum(len(c.get(f, [])) for c in colors for f in NAME_FIELDS)
    if meta.get("count_unique") != len(colors) or meta.get("count_raw") != expect:
        errors.append(f"meta counts stale: {meta} (expected {len(colors)}/{expect})")

    page = INDEX_HTML.read_text(encoding="utf-8")
    if "<?xml" in page:
        errors.append("index.html contains an <?xml?> declaration inside HTML")
    if page.count(MAP_BEGIN) != 1 or page.count(MAP_END) != 1:
        errors.append("index.html: COLORMAP markers missing or duplicated")
    else:
        cells = map_cells(page)
        centers = []
        for pts, fill, hx in cells:
            if fill != hx:
                errors.append(f"map: fill {fill} != data-hex {hx}")
            cx = sum(p[0] for p in pts) / 6
            cy = sum(p[1] for p in pts) / 6
            centers.append((round(cx, 1), round(cy, 1)))
            for p in pts:
                if abs(math.dist(p, (cx, cy)) - HEX_R) > 0.02:
                    errors.append(f"map: {hx} is not a regular hexagon")
                    break
        if len(set(centers)) != len(centers):
            errors.append("map: two polygons share a position")
        in_map = [hx for _, _, hx in cells]
        if sorted(in_map) != sorted(hexes):
            miss = set(hexes) - set(in_map)
            extra = set(in_map) - set(hexes)
            errors.append(f"map and colors.json differ: missing {sorted(miss)[:10]} extra {sorted(extra)[:10]}")
    for e in errors[:50]:
        print("ERROR", e)
    print(f"check: {len(colors)} colors, {len(errors)} errors, {len(warnings)} warnings "
          "(same name on several hexes; see okf/data/known-issues.md)")
    return 1 if errors else 0


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "check"
    if cmd == "import":
        cmd_import()
    elif cmd == "build":
        cmd_build()
    elif cmd == "check":
        sys.exit(cmd_check())
    elif cmd == "all":
        cmd_import()
        cmd_build()
        sys.exit(cmd_check())
    else:
        sys.exit(__doc__)
